name: audio_widget_demo
description: A demonstration of the audio widget.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider_architecture: 1.0.5
  audioplayers: ^0.14.0
  audio_widget:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/demo.mp3