name: audio_widget
description: Audio player widget for any platform, not an audio plugin itself but a skin to use with one.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: